### ISSUE TITLE
SQL file is broken

### ISSUE THREAD

**Issue by aliceric27** [Fraysa/Destiny#3]
I lost account,character,item in my SQL when i'm using MySQL Workbench import it.

![image](https://user-images.githubusercontent.com/30149653/28790988-80a4e5a6-765d-11e7-8dcf-e3e8a0426df2.png)

**Comment by TehCupcakes** [comment]
mcdb is a special database that basically contains a bunch of information from the wz files, so it's a replacement for wz loading. The main db for your server should _not_ be named mcdb - basically any other name will work.

The main db sql is baked in to the source code, so you cannot import it manually at the time. Delete your Configuration.ini and run the server to run the setup again, or run the executable with "setup" as an argument.

**Comment by TehCupcakes** [comment]
In other news, there was actually a typo in the db setup script that might have prevented it from creating, if you did run the set up. I pushed a fix for that, so make sure you have the latest version and try running the setup again. You may have to delete any existing database that you created initially.

**Comment by Fraysa** [comment]
Matter was solved & answer was given, closed.

**Comment by Nyuku** [comment]
The error in the script still persists. This has not been fixed.
"Incorrect table definition; there can be only one auto column and it must be defined as a key"

Fixed by just adding the primary key set when it creates the account table. May be something that just happens to me, but it's worth commenting in here.
